### ISSUE TITLE
How does the file stealer work???

### ISSUE THREAD

**Issue by testacc222** [Itroublve/ItroublveTSC#143]
So i want to test this on my VM and i don't really understand how to specify file directory in C#.
I tried doing "C:\Users\User\Documents" but it did not work.
Can someone explain please?
Thanks!

**Comment by Itroublve** [comment]
You won't be able to run the stealer on your VM due to the anti vm...

Also the URI to your documents folder is incorrect and shall be formated like this -> @"the path you given with the quotations", obviously the users won't be named User unless you're testing, but examples are given on how to retrieve the environment.username...

Also, I'm uncertain about how well it works with large files so you'll have to try/error.
